version: '3.4'
services:

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass JQODI9u1uioasdjkl][]12039dasjkl!@((Adlakjsdl))
    volumes:
      - cache:/data

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT=${APP_PORT}
    command: sh -c  "npm run db-reset && npm run migrate && npm run dev"
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/local/apps/app
      - ignore:/usr/local/apps/app/node_modules
      
volumes:
  db:
    driver: local
  cache:
    driver: local
  ignore: