FROM node:16-alpine

WORKDIR /usr/local/apps/app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
COPY .env ./.env

RUN npm ci
RUN mv node_modules ../node_modules
ENV PATH=/usr/local/apps/node_modules/.bin:$PATH

COPY ./src ./src

EXPOSE ${PORT}

ENTRYPOINT []